version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${ADOPTME_POSTGRES_DB}
      - POSTGRES_USER=${ADOPTME_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ADOPTME_POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
