# Generated by Django 3.1.3 on 2020-12-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_status_and_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(null=True, upload_to='pets'),
        ),
    ]
