from api.serializers.animal import AnimalSerializer, AnimalCreateSerializer, AnimalDetailSerializer
from api.serializers.auth import RegistrationSerializer
from api.serializers.adoptionstatus import AdoptionStatusSerializer
from api.serializers.vaccine import VaccineSerializer, VaccineBasicSerializer
from api.serializers.vaccination import VaccinationBasicSerializer
